{% set name = "libbson" %}
{% set version = "1.23.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mongodb/mongo-c-driver/releases/download/{{ version }}/mongo-c-driver-{{ version }}.tar.gz
  sha256: 260dc2207881ccbe7b79b1fa6b3ba84ab9be94eb93d4beefbbe8a6cb562947ed
  patches:
    - fix-malloc-osx.patch  # [osx]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/include/libbson-1.0/bson/bson.h      # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/libbson-1.0.pc         # [unix]
    - test -f ${PREFIX}/lib/libbson-1.0${SHLIB_EXT}          # [unix]
    - if not exist %LIBRARY_INC%\libbson-1.0\bson\bson.h (exit 1)     # [win]
    - if not exist %LIBRARY_LIB%\bson-1.0.lib (exit 1)    # [win]
    - if not exist %LIBRARY_BIN%\bson-1.0.dll (exit 1)    # [win]

about:
  home: https://github.com/mongodb/mongo-c-driver
  license: Apache-2.0
  license_file: COPYING
  summary: A library providing useful routines related to building, parsing, and iterating BSON documents.

extra:
  recipe-maintainers:
    - Tobias-Fischer
