{% set name = "libbson" %}
{% set version = "1.19.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mongodb/mongo-c-driver/releases/download/{{ version }}/mongo-c-driver-{{ version }}.tar.gz
  sha256: 23c365d319f0a53af81dd7d56f35e90c24ec32a21823c2f36c5d8c2d1edcdd6f

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/include/libbson-1.0/bson/bson.h      # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/libbson-1.0.pc         # [unix]
    - test -f ${PREFIX}/lib/libbson-1.0${SHLIB_EXT}          # [unix]
    - if not exist %LIBRARY_INC%\libbson-1.0\bson\bson.h (exit 1)     # [win]
    - if not exist %LIBRARY_LIB%\bson-1.0.lib (exit 1)    # [win]
    - if not exist %LIBRARY_BIN%\bson-1.0.dll (exit 1)    # [win]

about:
  home: https://github.com/mongodb/mongo-c-driver
  license: Apache-2.0
  license_file: COPYING
  summary: A library providing useful routines related to building, parsing, and iterating BSON documents.

extra:
  recipe-maintainers:
    - Tobias-Fischer
